drop database if exists bdChansons;
create database if not exists bdChansons;

use bdChansons;

create table Album
(
	id int auto_increment primary key,
    nom varchar(100),
    lienImage varchar(500)
);

create table Tag
(
	id int primary key,
    libelle varchar(50)
);

create table Interprete
(
	id int auto_increment primary key,
    nom varchar(60),
    prenom varchar(60),
    nomScene varchar(60)
);

create table Chanson
(
	id int auto_increment primary key,
    nom varchar(50),
    dateSortie varchar(50),
    genre varchar(50),
    duree varchar(50),
    meilleurePlace varchar(50),
    paroles varchar(5000),
    idAlbum int(4),
    foreign key (idAlbum) references Album(id)
);

create table Tagger
(
	idChanson int,
    idTag int,
    primary key (idChanson, idTag),
    foreign key (idChanson) references Chanson(id),
    foreign key (idTag) references Tag(id)
);

create table Chanter
(
	idChanson int,
    idInterprete int,
    primary key (idChanson, idInterprete),
    foreign key (idChanson) references Chanson(id),
    foreign key (idInterprete) references Interprete(id)
);

create table User
(
    idUser int primary key auto_increment,
    userLog varchar(30),
    mdp varchar(30),
    nom varchar(50),
    prenom varchar(50)
);

INSERT INTO Album (nom, lienImage) VALUES 
('The Immaculate Collection', 'Project\Images\1.TheIMMACULATECollection.jpg'),
('Singulier 81 - 89', 'Project\Images\2.Singulier81-89.jpg'),
('Gang', 'Project\Images\3.Gang.jpg'),
('Thriller', 'Project\Images\4.Thriller.jpg'),
('Paris, France', 'Project\Images\5.ParisFrance.jpg'),
("L'aventurier", 'Project\Images\6.Laventurier.jpg'),
('The Joshua Tree', 'Project\Images\7.TheJoshuaTree.jpg'),
('The Final', 'Project\Images\8.TheFinal.jpg'),
('Greatest Hits II (2011 Remaster)', 'Project\Images\9.GreatestHitsIII.jpg'),
('Hunting High and Low', 'Project\Images\10.HuntingHighAndLow.jpg'),
('Parade - Music from the Motion Picture Under the Cherry Moon', 'Project\Images\11.ParadeMusicFromTheMotionPicture.jpg'),
('Best Of Blondie', 'Project\Images\12.BestOfBlondie.jpg'),
('Liberté', 'Project\Images\13.Liberte.jpg'),
("Let's Dance", 'Project\Images\14.LetsDance.jpg'),
('Sweet Dreams (Are Made Of This)', 'Project\Images\15.SweetDreams.jpg'),
('True Colors: The Best Of Cyndi Lauper', 'Project\Images\16.TrueColors.jpg'),
('Katrina & The Waves', 'Project\Images\17.KatrinaAndTheWaves.jpg'),
('Jeanne Mas', 'Project\Images\18.JeanneMas.jpg'),
('François', 'Project\Images\19.Francois.jpg'),
('Nena', 'Project\Images\20.Nena.jpg'),
('Eternal Flame: The Best Of', 'Project\Images\21.EternalFlame.jpg'),
('Back To Front', 'Project\Images\22.BackToFront.jpg'),
('Born to Be Alive (Extended Version)', 'Project\Images\23.BornToBeAlive.jpg'),
('Chinese Wall', 'Project\Images\24.ChineseWall.jpg'),
('Les 50 Plus Belles Chansons', 'Project\Images\25.Les50PusBellesChansons.jpg'),
('Au top des années 80, vol. 1 (30 titres + 5 maxis)', 'Project\Images\26.AuTopDesAnnes80.jpg'),
('The Very Best of Daryl Hall / John Oates', 'Project\Images\27.VeryBestOfDaryllHall&JohnOates.jpg'),
('The Best of Me', 'Project\Images\28.TheBestOfMe.jpg'),
('Africa', 'Project\Images\29.BestOfRoseLaurens.jpg'),
('The Greatest Hits Collection - Collector Edition', 'Project\Images\30.TheGreatestHitsCollection.jpg'),
('The Best Of The Bangles', 'Project\Images\31.TheBestOfTheBangles.jpg'),
("That's The Way I Like It: The Best of Dead Or Alive", 'Project\Images\32.DeadOrAlive.jpg'),
('Love On The Beat', 'Project\Images\33.LoveOfTheBeat.jpg'),
('Whitney', 'Project\Images\34.IWannaDanceWithSimebody.jpg'),
('Samantha Fox Greatest Hits', 'Project\Images\35.TouchMe.jpg'),
('Gypsy Honeymoon: The Best Of Kim Carnes', 'Project\Images\36.BetteDavisEyes.jpg'),
('Beds Are Burning (Remastered)', 'Project\Images\38.BedsAreBurning.jpg'),
('Evidemment', 'Project\Images\39.EllaElleLa.jpg'),
('Too Shy-The Singles...And More', 'Project\Images\40.TooShy.jpg'),
('Forever Young', 'Project\Images\41.ForeverYoung.jpg'),
('Best of', ''),
('Irresistible Princess', 'Project\Images\43.Ouragan.jpg'),
('Best of Jakie Quartz (Le meilleur des années 80)', 'Project\Images\44.MiseAuPoint.jpg'),
('The Singles (Expanded)', 'Project\Images\45.YouCantHurryLove.jpg'),
('The Very Best Of Sting And The Police', 'Project\Images\46.MessageInABottle.jpg'),
('Once Upon A Time (Super Deluxe)', 'Project\Images\47.DontYou(ForgetAboutMe).jpg'),
('Essential', 'Project\Images\48.ItsMyLife.jpg'),
('Only Yazoo - The Best of Yazoo', 'Project\Images\49.DontGo.jpg'),
('Soul Love Vol. 1 - Soul Love Vol. 2 - Soul Love Vol. 3 [Clean]', 'Project\Images\50.SmoothOperator.jpg'),
('Kick (Remastered 2011)', 'Project\Images\51.NeedYouTonight.jpg'),
('Songs From The Big Chair', 'Project\Images\52.Shout.jpg'),
('All The Best', 'Project\Images\53.DontYouWantMe.jpg'),
('The Very Best Of Soft Cell', 'Project\Images\54.TaintedLove.jpg'),
('The Age Of Plastic', 'Project\Images\55.VideoKilledTheRadioStar.jpg'),
('Best Of', 'Project\Images\56.SansContrefacon(Mix2001).jpg'),
('Toto IV', 'Project\Images\57.Africa.jpg'),
('True Blue', 'Project\Images\58.LaIslaBonita.jpg'),
('Eve lève-toi', 'Project\Images\59.EveLeveToi.jpg'),
("Terence Trent D'Arby's Greatest Hits", 'Project\Images\60.WishingWell.jpg'),
('Never for Ever', 'Project\Images\61.Babooshka.jpg'),
('Sultans Of Swing - The Very Best Of Dire Straits', 'Project\Images\63.SultansOfSwing.jpg'),
('Le Banana Split (Remix Album)', 'Project\Images\64.LeBananaSplit.jpg'),
('50 Great Songs', 'Project\Images\65.YourLoveIsKing.jpg'),
('Isabelle Adjani', 'Project\Images\66.PullMarine.jpg'),
("Nothing's Gonna Change My Love For You", 'Project\Images\67.NothingsGonnaChangeMyLoveForYou.jpg'),
('Une Presence', 'Project\Images\68.UnePresence.jpg'),
('80s Power Ballads', 'Project\Images\69.80sPowerBallads.jpg'),
('A Collection of Roxette Hits! Their 20 Greatest Songs!', 'Project\Images\70.ACollectionOfRoxetteHits.jpg'),
('Purple Rain [Explicit]', 'Project\Images\71.PurpleRain.jpg'),
('LOVE', 'Project\Images\72.LOVE.png'),
('Best Of 70', 'Project\Images\73.BestOf70MichelSardou.jpg'),
('Maximum Joy', 'Project\Images\74.MaximumJoyFrankieGoesToHollywood.jpg'),
('Whiter Shade of Pale and More Million Sellers', 'Project\Images\75.WhiterShadeOfPaleAndMoreMillionSellers.jpg'),
('Les années 80 en France', 'Project\Images\76.LesAnnées80EnFrance.jpg'),
('One Step Beyond', 'Project\Images\77.OneStepBeyondMadness.jpg'),
("T'es OK, t'es bath, t'es In", 'Project\Images\78.T-esOkT-esBathT-esInOttawan.jpg'),
('Pour Me Comprendre (40 titres)', 'Project\Images\79.PourMeComprendre.jpg'),
('77/87', 'Project\Images\80.77-87FrancisCabrel.jpg'),
('Les indispensables', 'Project\Images\81.LesIndispensables.jpg'),
('Chants zazous [Explicit]', 'Project\Images\82.ChantsZazous.jpg'),
('Fame (Original Motion Picture Soundtrack)', 'Project\Images\83.Fame.jpg'),
('ABBA Gold', 'Project\Images\84.ABBAGoldABBA.jpg'),
('Poses', 'Project\Images\85.Poses.jpg'),
('Spacer (Monsieur Willy Remix)', 'Project\Images\86.Spacer.jpg'),
("Quand t'es dans le désert", 'Project\Images\87.QuandT-esDansLeDésert.jpg'),
('Antisocial - Le Meilleur Des Années CBS', 'Project\Images\88.Antisocial-LeMeilleurDesAnnéesCBS.jpg'),
('The Meilleur Of Renaud', 'Project\Images\89.TheMeilleurOfRenaud.jpg'),
('Alors regarde', 'Project\Images\90.AlorsRegarde.jpg'),
('Les grands moments - Best Of', 'Project\Images\91.LesGrandsMomments-BestOfMichelSardou.jpg'),
('Best of Philippe Lafontaine (Le meilleur des années 80)', 'Project\Images\92.BestOfPhilippeLafontaine.jpg'),
('Besoin De Rien, Envie De Toi', 'Project\Images\93.Besoin-de-rien-envie-de-toi.jpg'),
("L'essentiel", 'Project\Images\94.Lessentiel.jpg'),
("Ma collection 80's: Hervé Cristiani", 'Project\Images\95.MaCollection80HerveCristiani.png'),
('Quand la musique est bonne', 'Project\Images\96.QuandLaMusiqueEstBonne.jpg'),
('Best Of Catherine Lara', 'Project\Images\97.BestOfCatherineLara.jpg'),
('Le son des années 80', 'Project\Images\99.Stars80LAlbumAnniversaire.jpg'),
('Stars 80 l’album anniversaire !', 'Project\Images\99.Stars80LAlbumAnniversaire.jpg'),
('Best of Corynne Charby', 'Project\Images\100.BestOfCorynneCharby.jpg');

INSERT INTO Interprete(nom, prenom, nomScene) VALUES
('Ciccone', 'Madonna', 'Madonna'),
('Goldman', 'Jean-Jacques', 'Jean-Jacques Goldman'),
('Smet', 'Jean-Philippe', 'Johnny Halliday'),
('Jackson', 'Michael', 'Michael Jackson'),
('Gall', 'Isabelle', 'France Gall'),
(null, null, 'Indochine'),
(null, null, 'U2'),
(null, null, 'Wham!'),
(null, null, 'Queen'),
(null, null, 'A-HA'),
('Nelson', 'Pince', 'Prince'),
(null, null, 'Blondie'),
('Montagné', 'Gilbert', 'Gilbert Montagné'),
('Jones', 'David', 'David Bowie'),
(null, null, 'Eurythmics'),
('Lennox', 'Ann', 'Annie Lennox'),
('Stewart', 'David', 'Dave Stewart'),
('Lauper', 'Cynthia', 'Cyndi Lauper'),
(null, null, 'Katrina & The Waves'),
('Mas', 'Jeanne', 'Jeanne Mas'),
('Fritsch-Mentrop', 'Claudie', 'Desireless'),
('Kerner', 'Gabriele', 'NENA'),
(null, null, 'The Bangles'),
('Richie', 'Lionel', 'Lionel Richie'),
('Hernandez', 'Patrick', 'Patrick Hernandez'),
('Bailey', 'Philip', 'Philip Bailey'),
('Collins', 'Philip', 'Phil Collins'),
('Balavoine', 'Daniel', 'Daniel Balavoine'),
(null, null, 'Début de soirée'),
('Hohl', 'Daryl', 'Daryl Hall'),
('Oates', 'John', 'John Oates'),
('Astley', 'Richard', 'Rick Astley'),
('Podwojny', 'Rose', 'Rose Laurens'),
(null, null, 'Bananarama'),
(null, null, 'The Bangles'),
(null, null, 'Dead or Alive'),
('Ginsberg', 'Lucien', 'Serge Gainsbourg'),
('Houston', 'Whitney', 'Whitney Houston'),
('Fox', 'Samantha', 'Samantha Fox'),
(null, null, 'Midnight Oil'),
(null, null, 'Kajagoogoo'),
(null, null, 'Alphaville'),
(null, null, 'Téléphone'),
('Grimaldi', 'Stéphanie', 'Stéphanie de Monaco'),
('Cuchet', 'Jacqueline', 'Jakie Quartz'),
(null, null, 'The Police'),
(null, null, 'Simple Minds'),
(null, null, 'Talk Talk'),
(null, null, 'Yazoo'),
('Adu', 'Helen', 'Sade'),
(null, null, 'INXS'),
(null, null, 'Tears For Fears'),
(null, null, 'The Human League'),
(null, null, 'Soft Cell'),
(null, null, 'The Buggles'),
('Gautier', 'Mylène', 'Mylène Farmer'),
(null, null, 'Toto'),
('Pietri', 'Nicole', 'Julie Pietri'),
('Howard', 'Terence', 'Sananda Maitreya'),
('Bush', 'Catherine', 'Kate Bush'),
('Séchan', 'Renaud', 'Renaud'),
(null, null, 'Dire Straits'),
('Ribeiro Furtado Tavares de Vasconcelos', 'Vanda', 'Lio'),
('Adjani', 'Isabelle', 'Isabelle Adjani'),
('Medeiros', 'Glenn', 'Glenn Medeiros'),
('Feldman', 'François', 'François Feldman'),
('Jamison', 'Joniece', 'Joniece Jamison'),
(null, null, 'Berlin'),
(null, null, 'Roxette'),
('Medley', 'William', 'Bill Medley'),
('Warnes', 'Jennifer', 'Jennifer Warnes'),
('Sardou', 'Michel', 'Michel Sardou'),
(null, null, 'Frankie Goes to Hollywood'),
(null, null, 'Imagination'),
('Anyankor', 'Béatrice', 'Bibie'),
(null, null, 'Madness'),
(null, null, 'Ottawan'),
('Hamburger', 'Michel', 'Michel Berger'),
('Cabrel', 'Francis', 'Francis Cabrel'),
(null, null, 'Le Grand Orchestre du Splendid'),
('Gotainer', 'Richard', 'Richard Gotainer'),
('Cara', 'Irene', 'Irene Cara'),
(null, null, 'ABBA'),
('Le Govic', 'Alain', 'Alain Chamfort'),
('Chancel', 'Annie', 'Sheila'),
('Capdevielle', 'Jean-Patrick', 'Jean-Patrick Capdevielle'),
(null, null, 'The Trust'),
('Bruel-Benguigui', 'Patrick', 'Patrick Bruel'),
('Lafontaine', 'Philippe', 'Philippe Lafontaine'),
(null, null, 'Peter & Sloane'),
('Lunghini', 'Elsa', 'Elsa'),
('Cristiani', 'Hervé', 'Hervé Cristiani'),
('Bodet', 'Catherine', 'Catherine Lara'),
(null, null, 'Partenaire Particulier'),
(null, null, 'Cookie Dingler'),
('Charbit', 'Corinne', 'Corynne Charby');

insert into Chanson(nom,dateSortie,duree,meilleurePlace,paroles,genre) Values
('Like a Virgin','1984','03:11','top 5 hit-parade',null,'Pop'),
('Au bout de mes rêves','1982','03:46','top 1 hit-parade',null,'Variété française'),
("Thriller",'1982','05:58','top 1 hit-parade',null,'Pop Rock'),
("Il jouait du piano debout",'1980','04:33','top 6 hit-parade',null,'Rock'),
("L'aventurier",'1982','03:51','top 2 hit-parade',null,'Rock'),
("With Or Without You",'1987','04:56','top 10 hit-parade',null,'Rock'),
("Wake Me Up Before You Go-Go",'1984','03:51','top 17 hit-parade',null,'Pop'),
("I Want To Break Free",'1984','04:18','top 9 hit-parade',null,'Pop Rock'),
("Take on Me",'1985','03:45','top 1 hit-parade',null,'Pop'),
("Kiss",'1986','03:46','top 6 hit-parade',null,'Pop'),
("Call Me",'1980','03:33','top 4 hit-parade',null,'Rock'),
("Les sunlights des tropiques",'1984','03:58','top 14 hit-parade',null,'Variété française'),
("Let's Dance",'1983','04:07','top 2 hit-parade',null,'Pop Rock'),
("Sweet Dreams (Are Made of This)",'1983','03:37','top 1 hit-parade',null,'Pop'),
("Girls Just Want to Have Fun",'1983','03:56','top 10 hit-parade',null,'Pop'),
("Walking On Sunshine",'1983','03:59','top 8 hit-parade',null,'Pop'),
("Toute première fois",'1985','04:18','top 1 hit-parade',null,'Pop'),
("Voyage voyage",'1989','04:26','top 2 hit-parade',null,'Pop'),
("99 Luftballons",'1983','03:52','top 12 hit-parade',null,'Pop Rock'),
("Eternal Flame",'1988','04:00','top 12 hit-parade',null,'Rock'),
("All Night Long",'1983','04:19','top 4 hit-parade',null,'R&B'),
("Born to Be Alive",'1983','05:54','top 2 hit-parade',null,'Pop'),
("Easy Lover",'1984','05:04','top 2 hit-parade',null,'Rock'),
("Sauver l'amour",'1985','04:22','top 5 hit-parade',null,'Variété française'),
("Nuit de folie",'1989','04:13','top 1 hit-parade',null,'Pop'),
("Maneater",'1982','04:32','top 5 hit-parade',null,'Pop'),
("Never Gonna Give You Up",'1987','03:34','top 1 hit-parade',null,'Pop'),
("Africa",'1983','03:36','top 5 hit-parade',null,'Pop'),
("Venus",'1986','03:29','top 4 hit-parade',null,'Pop'),
("Walk Like an Egyptian",'1986','03:26','top 9 hit-parade',null,'Pop'),
("You Spin Me Round",'1985','03:16','top 9 hit-parade',null,'Pop'),
("Love On The Beat",'1984','08:04','top 3 hit-parade',null,'Variété française'),
("I Wanna Dance with Somebody",'1987','04:53','top 7 hit-parade',null,'Pop'),
("Touch Me (I Want Your Body)",'1986','03:42','top 4 hit-parade',null,'Pop Rock'),
("Bette Davis Eyes",'1981','03:46','top 2 hit-parade',null,'Pop'),
("Billie Jean",'1982','04:54','top 1 hit-parade',null,'Rock'),
("Ella, elle l'a",'1987','04:51','top 2 hit-parade',null,'Variété française'),
("Too Shy",'1983','03:41','top 6 hit-parade',null,'Pop'),
("Forever Young",'1984','03:46','top 13 hit-parade',null,'Pop Rock'),
("Un autre monde",'1984','04:31','top 1 hit-parade',null,'Pop Rock'),
("Ouragan",'1986','04:22','top 1 hit-parade',null,'Pop'),
("Mise au point",'1983','04:42','top 1 hit-parade',null,'Rock'),
("You Can't Hurry Love ",'1982','02:54','top 13 hit-parade',null,'Soul'),
("Message In A Bottle",'1979','04:49','top 19 hit-parade',null,'Rock'),
("Don't You (Forget About Me)",'1985','04:23','top 24 hit-parade',null,'Rock'),
("It's My Life",'1984','03:53','top 25 hit-parade',null,'Pop Rock'),
("Don't Go",'1982','03:06','top 1 hit-parade',null,'Pop'),
("Smooth Operator",'1984','04:58','top 9 hit-parade',null,'R&B'),
("Need You Tonight",'1987','03:01','top 14 hit-parade',null,'Pop Rock'),
("Shout",'1984','06:34','top 19 hit-parade',null,'Pop Rock'),
("Don't You Want Me",'1981','03:57','top 20 hit-parade',null,'Pop Rock'),
("Tainted Love",'1981','02:40','top 3 hit-parade',null,'Pop Rock'),
("Video Killed The Radio Star",'1979','04:14','top 23 hit-parade',null,'Pop Rock'),
("Sans contrefaçon",'1987','04:17','top 23 hit-parade',null,'Variété française'),
("Africa",'1982','04:55','top 13 hit-parade',null,'Pop'),
("La Isla Bonita",'1986','04:03','top 1 hit-parade',null,'Pop'),
("Eve lève-toi",'1987','04:32','top 1 hit-parade',null,'Pop'),
("Wishing Well",'1987','03:31','top 40 hit-parade',null,'Pop'),
("Babooshka",'1980','03:31','top 20 hit-parade',null,'Pop'),
("Dès que le vent soufflera",'1983','04:26','top 96 hit-parade',null,'Rock'),
("Sultans Of Swing",'1978','05:47','top 7 hit-parade',null,'Rock'),
("Le Banana Split",'1980','02:33','top 1 hit-parade',null,'Pop'),
("Your Love Is King",'1984','03:38','top 6 hit-parade',null,'Pop'),
("Pull marine",'1984','03:55','top 3 hit-parade',null,'Variété française'),
("Nothing's Gonna Change My Love For You",'1985','03:51','top 1 hit-parade',null,'Pop'),
("Joue Pas",'1989','06:46','top 20 hit-parade',null,'Pop'),
("Take My Breath Away",'1986','06:46','top 2 hit-parade',null,'Pop'),
("Listen to Your Heart",'1988','05:15','top 11 hit-parade',null,'Pop'),
("Purple Rain",'1984','08:40','top 2 hit-parade',null,'Pop'),
("The Time of My Life",'1987','04:49','top 1 hit-parade',null,'Pop'),
("Être une femme",'1981','04:15','top 5 hit-parade',null,'Variété française'),
("Relax",'1984','03:58','top 6 hit-parade',null,'Pop'),
("Just an Illusion",'1982','06:28','top 10 hit-parade',null,'Pop'),
('Boule de flipper', '1987', '03:27', 'Top 17 Hit-Parade', null, 'Pop'),
('Femme libérée', '1984', '03:44', 'Top 2 Hit-Parade', null, 'Variété française reggae'),
('Partenaire Particulier', '1985', '04:06', 'Top 3 Hit-Parade', null, 'Pop'),
('Nuit magique', '1986', '04:36', 'Top 13 Hit-Parade', null, 'Variété française'),
('Quand la musique est bonne', '1982', '03:52', 'Top 1 Hit-Parade', null, 'Variété française / Pop rock'),
('Il est libre Max', '1981', '03:16', 'Top 105 Hit-Parade', null, 'Pop rock'),
("T'en va pas", '1986', '05:28', 'Top 1 Hit-Parade', null, 'Pop'),
('Besoin de rien, envie de toi', '1958', '03:42', 'Top 1 Hit-Parade', null, 'Variété française'),
('Cœur de loup', '1988', '03:43', 'Top 1 Hit-Parade', null, 'Pop'),
('Les Lacs du Connemara', '1981', '06:01', 'Top 117 Hit-Parade', null, 'Variété française'),
('Place des grands hommes', '1989', '4:29', 'Top 4 Hit-Parade', null, 'Pop Rock'),
("Marche à l'ombre", '1980', '03:18', null, null, 'Variété française'),
('Antisocial', '1980', '05:09', 'Top 34 du Hit-Parade', null, 'Rock'),
("Quand t'es dans le désert", '1979', '03:55', null, null, 'Rock'),
('Spacer', '1980', '03:57', 'Top 86 Hit-Parade', null, 'Pop'),
('Manuvera', '1979', '06:43', 'Top 82 Hit-Parade', null, 'Variété française / Pop'),
('Gimme! Gimme! Gimme! (A Man After Midnight)', '1979', '04:49', 'Top 2 Hit-Parade', null, 'Pop'),
('Fame', '1980', '05:16', 'Top 2 Hit-Parade', null, 'Pop'),
('La Mambo du décalco', '1982', '03:34', 'Top 28 Hit-Parade', null, 'Pop'),
('La Salsa du démon', '1980', '04:17', 'Top 42 Hit-Parade', null, 'Ska'),
("L'encre de tes yeux", '1980', '03:06', null, null, 'Variété française'),
('La groupie du pianiste', '1980', '04:41', 'Top 17 Hit-Parade', null, 'Pop'),
("T'es OK, T'es Bath, T'es In", '1980', '03:22', null, null, 'R&B'),
('One Step Beyond', '1979', '02:18', 'Top 1 Hit-Parade', null, 'Pop'),
('Tout simplement (tout doucement)', '1985', '04:10', 'Top 2 Hit-Parade', null, 'Variété française');

insert into User(id, userLog, mdp) Values
(0, "admin", "admin");

select * from interprete;